document.write(" <div style=\"float:left; padding-left: 2%;\">");
document.write(" <a href=\"http://www.ymcaust.ac.in\" target=\"_system\">");
document.write(" <img style=\"max-width: 120px ; max-height: 120px ;\" src=\"images/ymca.png\"></a></div>");
document.write(" <div><style>.social-container {");
document.write(" width: 100% ;");
document.write(" position: relative;");
document.write(" z-index: 1000;");
document.write(" align-self: center;");
document.write(" align-items: center;");
document.write(" padding: 0 30px 0 30px ;");
document.write(" vertical-align: bottom; }");
document.write(" ");
document.write(" .social {");
document.write(" margin-top: 10px;  margin-right: 15px ;");
document.write(" float: right; }");
document.write(" ");
document.write(" a.social > div {");
document.write(" height: fit-content ; width: fit-content ;");
document.write(" text-decoration: none;");
document.write(" transition: background 0.2s ease ;}");
document.write(" .social > #facebook {");
document.write(" background: url(\"images/logotype3_nor.png\");");
document.write(" width: 32px ;");
document.write(" height: 32px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" .social > #facebook:hover {");
document.write(" background: url(\"images/logotype3.png\");");
document.write(" width: 32px ;");
document.write(" height: 32px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" .social > #twitter {");
document.write(" background: url(\"images/twitter28_nor.png\");");
document.write(" width: 32px ;");
document.write(" height: 32px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" .social > #twitter:hover {");
document.write(" background: url(\"images/twitter28.png\");");
document.write(" width: 32px ;");
document.write(" height: 32px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" .social > #googleplus {");
document.write(" background: url(\"images/youtube28_nor.png\");");
document.write(" width: 32px ;");
document.write(" height: 32px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" .social > #googleplus:hover {");
document.write(" background: url(\"images/youtube28.png\");");
document.write(" width: 32px ;");
document.write(" height: 32px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" </style>");
document.write(" <div class=\"social-container\">");
document.write(" <a href=\"https://www.facebook.com/culmyca\" class=\"social\" target=\"_system\"> ");
document.write(" <div id=\"facebook\"></div></a>");
document.write(" <a href=\"https://twitter.com/elementsculmyca\" class=\"social\" target=\"_system\">");
document.write(" <div id=\"twitter\"></div></a>");
document.write(" <a href=\"https://www.youtube.com/channel/UCVMMQ2TqmmE5X610wFIEMPw\" class=\"social\" target=\"_system\">");
document.write(" <div id=\"googleplus\"></div></a></div></div>");
// document.write(" <script src=\"js/ripple.js\"></script>");
// document.write(" <script src=\"js/jquery.validate.min.js\"></script>");
// document.write(" <script src=\"js/jquery.colorbox-min.js\"></script>");
// document.write(" <script src=\"js/hide.js\"></script>");
