document.write(" <div style=\"float:left; padding-left: 2%;\">");
document.write(" <a class=\"\" href=\"http://www.ymcaust.ac.in\" target=\"_system\">");
document.write(" <img src=\"images/iisc.png\"></a></div>");
document.write(" <div><style>.social-container {");
document.write(" width: 100% ;");
document.write(" position: relative;");
document.write(" z-index: 1000;");
document.write(" align-self: center;");
document.write(" align-items: center;");
document.write(" padding: 0 30px 0 30px ;");
document.write(" vertical-align: bottom; }");
document.write(" ");
document.write(" .social {");
document.write(" margin-top: 10px; ");
document.write(" float: right; }");
document.write(" ");
document.write(" a.social > div {");
document.write(" height: 50px ; width: 50px ;");
document.write(" text-decoration: none;");
document.write(" transition: background 0.2s ease ;}");
document.write(" .social > #facebook {");
document.write(" background: url(\"images/facebook56_nor.png\");");
document.write(" width: 50px ;");
document.write(" height: 50px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" .social > #facebook:hover {");
document.write(" background: url(\"images/facebook56.png\");");
document.write(" width: 50px ;");
document.write(" height: 50px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" .social > #twitter {");
document.write(" background: url(\"images/twitter28_nor.png\");");
document.write(" width: 50px ;");
document.write(" height: 50px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" .social > #twitter:hover {");
document.write(" background: url(\"images/twitter28.png\");");
document.write(" width: 50px ;");
document.write(" height: 50px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" .social > #googleplus {");
document.write(" background: url(\"images/google116_nor.png\");");
document.write(" width: 50px ;");
document.write(" height: 50px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" .social > #googleplus:hover {");
document.write(" background: url(\"images/google116.png\");");
document.write(" width: 50px ;");
document.write(" height: 50px ;");
document.write(" background-repeat: no-repeat; }");
document.write(" </style>");
document.write(" <div class=\"social-container\">");
document.write(" <a href=\"https://www.facebook.com\" class=\"social\" target=\"_system\"> ");
document.write(" <div id=\"facebook\"></div></a>");
document.write(" <a href=\"https://www.twitter.com\" class=\"social\" target=\"_system\">");
document.write(" <div id=\"twitter\"></div></a>");
document.write(" <a href=\"https://plus.google.com\" class=\"social\" target=\"_system\">");
document.write(" <div id=\"googleplus\"></div></a></div></div>");
document.write(" <script src=\"js/ripple.js\"></script>");
document.write(" <script src=\"js/jquery.validate.min.js\"></script>");
document.write(" <script src=\"js/jquery.colorbox-min.js\"></script>");
document.write(" <script src=\"js/hide.js\"></script>");
